"""initial schema: memories, entities, edges

Revision ID: f61a6110a7e6
Revises: 
Create Date: 2026-08-25 20:05:43.206614

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'f61a6110a7e6'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
